'use client';
import { useState } from 'react';
import TopNavbar from '@/components/layout/TopNavbar';
import {
  MASTER_STUDENTS, MASTER_TEACHERS, UNIVERSITY_STATS
} from '@/data/sharedMockData';

const REPORTS = [
  { id: 'RPT-001', name: 'Student Performance Report', icon: '🎓', desc: 'Complete student-wise CGPA, attendance, and skill progress summary.', category: 'Student' },
  { id: 'RPT-002', name: 'Faculty Performance Report', icon: '👨‍🏫', desc: 'Teaching scores, research output, and mentorship KPIs for all faculty.', category: 'Faculty' },
  { id: 'RPT-003', name: 'Attendance Analytics Report', icon: '📅', desc: 'Subject-wise and student-wise attendance trends for the semester.', category: 'Attendance' },
  { id: 'RPT-004', name: 'Course Health Report', icon: '📚', desc: 'Pass rates, grade distribution, and student feedback by course.', category: 'Course' },
  { id: 'RPT-005', name: 'Department Overview Report', icon: '🏢', desc: 'Executive summary of all departmental academic activities.', category: 'Department' },
  { id: 'RPT-006', name: 'Research Output Summary', icon: '🔬', desc: 'Publications, grants, and research project status for CIS faculty.', category: 'Research' },
  { id: 'RPT-007', name: 'Skill Development Report', icon: '🧠', desc: 'Student and departmental skill growth tracking and gap analysis.', category: 'Skills' },
  { id: 'RPT-008', name: 'Mentorship Progress Report', icon: '🤝', desc: 'Session logs, student progress, and mentor effectiveness metrics.', category: 'Mentorship' },
  { id: 'RPT-009', name: 'Semester Summary Report', icon: '📊', desc: 'Complete semester wrap-up: results, attendance, and highlights.', category: 'Semester' },
];

function buildDeptHeadReportContent(id: string): string {
  const now = new Date();
  const ts = now.toLocaleString('en-US', { dateStyle: 'full', timeStyle: 'short' });

  // Filter only for CIS department (Dept Head scope)
  const deptStudents = MASTER_STUDENTS.filter(s => s.departmentId === 'CIS');
  const deptTeachers = MASTER_TEACHERS.filter(t => t.departmentId === 'CIS');
  const atRiskStudents = deptStudents.filter(s => s.segment === 'at-risk');

  const header = `╔══════════════════════════════════════════════════════════════╗
  CIS DEPARTMENT — ACADEMIC REPORTS PORTAL
  Generated: ${ts}
  Generated By: Mr. Md. Sarwar Hossain Mollah (Head, CIS)
  System: EduVision AI ERP Platform
╚══════════════════════════════════════════════════════════════╝\n\n`;

  if (id === 'RPT-001') {
    const rows = deptStudents.map((s, i) =>
      `  ${String(i + 1).padStart(2, '0')}. ${s.name.padEnd(25)} | ${s.roll.padEnd(12)} | CGPA: ${s.cgpa.toFixed(2)} | Att: ${s.attendancePct}% | Status: ${s.segment}`
    ).join('\n');
    const avgCgpa = (deptStudents.reduce((a, b) => a + b.cgpa, 0) / deptStudents.length).toFixed(2);
    return `${header}🎓 CIS STUDENT PERFORMANCE REPORT — ${UNIVERSITY_STATS.semester}
Total Students Analyzed: ${deptStudents.length}
Department Average CGPA: ${avgCgpa}
At-Risk Students: ${atRiskStudents.length}

${'─'.repeat(80)}
${'  #'.padEnd(5)} ${'Student Name'.padEnd(25)} | ${'Roll'.padEnd(12)} | CGPA   | Attendance | Status
${'─'.repeat(80)}
${rows}
${'─'.repeat(80)}

AI INSIGHT:
  📌 Department average CGPA is ${avgCgpa}, which is highly competitive.
  ⚠️  ${atRiskStudents.length} student(s) identified as 'at-risk' requiring mentor scheduling.`;
  }

  if (id === 'RPT-002') {
    const rows = deptTeachers.map((t, i) =>
      `  ${String(i + 1).padStart(2, '0')}. ${t.name.padEnd(30)} | ${t.designation.padEnd(25)} | KPI: ${t.kpiScore}% | Courses: ${t.courses.length} | Students: ${t.totalStudents}`
    ).join('\n');
    return `${header}👨‍🏫 CIS FACULTY PERFORMANCE REPORT — ${UNIVERSITY_STATS.semester}
Total Faculty Evaluated: ${deptTeachers.length}

${'─'.repeat(100)}
${'  #'.padEnd(5)} ${'Faculty Name'.padEnd(30)} | ${'Designation'.padEnd(25)} | KPI Score | Courses | Total Students
${'─'.repeat(100)}
${rows}
${'─'.repeat(100)}

AI INSIGHT:
  📌 The faculty KPI average is above 80%, indicating strong instructional quality.
  ✅ Recommend updating course allocation based on specific expertise areas for next semester.`;
  }

  if (id === 'RPT-003') {
    const rows = deptStudents.map((s, i) => {
      const risk = s.attendancePct < 75 ? '🔴 CRITICAL' : '🟢 GOOD';
      return `  ${String(i + 1).padStart(2, '0')}. ${s.name.padEnd(25)} | ${s.roll.padEnd(12)} | Attendance: ${s.attendancePct}% | ${risk}`;
    }).join('\n');
    const avgAtt = Math.round(deptStudents.reduce((a, b) => a + b.attendancePct, 0) / deptStudents.length);
    return `${header}📅 CIS ATTENDANCE ANALYTICS REPORT — ${UNIVERSITY_STATS.semester}
Department Average Attendance: ${avgAtt}%

${'─'.repeat(80)}
${'  #'.padEnd(5)} ${'Student Name'.padEnd(25)} | ${'Roll'.padEnd(12)} | Overall Attendance | Status
${'─'.repeat(80)}
${rows}
${'─'.repeat(80)}

AI INSIGHT:
  📌 Average attendance (${avgAtt}%) meets the university minimum standard.
  ⚠️  ${deptStudents.filter(s => s.attendancePct < 75).length} student(s) have critical attendance below 75%. Issue warning letters.`;
  }

  if (id === 'RPT-006') {
    const totalPubs = deptTeachers.reduce((a, t) => a + t.researchPublications, 0);
    const rows = deptTeachers.map((t, i) =>
      `  ${String(i + 1).padStart(2, '0')}. ${t.name.padEnd(30)} | Publications: ${t.researchPublications} | Expertise: ${t.expertise.join(', ')}`
    ).join('\n');
    return `${header}🔬 CIS RESEARCH OUTPUT SUMMARY — ${UNIVERSITY_STATS.semester}
Total Departmental Publications (Active/Recent): ${totalPubs}

FACULTY RESEARCH BREAKDOWN:
${'─'.repeat(100)}
${rows}
${'─'.repeat(100)}

AI INSIGHT:
  📌 Research output is concentrated in AI and Data Science domains.
  ✅ Suggest allocating internal research grants to newer faculty to boost department-wide publication rates.`;
  }

  return `${header}📊 Report data generated successfully.\nTimestamp: ${ts}\nAI has analyzed the relevant dataset for ${id} inside the CIS scope.`;
}

export default function DeptHeadReportsPage() {
  const [generating, setGenerating] = useState<string | null>(null);
  const [activeReport, setActiveReport] = useState<{ id: string; name: string; content: string } | null>(null);

  const generate = (report: typeof REPORTS[0]) => {
    setGenerating(report.id);
    setTimeout(() => {
      const content = buildDeptHeadReportContent(report.id);
      setActiveReport({ id: report.id, name: report.name, content });
      setGenerating(null);
    }, 1200);
  };

  const handlePrint = () => {
    if (!activeReport) return;
    const win = window.open('', '_blank');
    if (!win) return;
    win.document.write(`<html><head><title>${activeReport.name}</title>
      <style>body{font-family:monospace;font-size:13px;padding:24px;white-space:pre-wrap;line-height:1.6;color:#0f172a;}
      h1{font-size:16px;}@media print{body{font-size:11px;}}</style></head>
      <body><pre>${activeReport.content}</pre></body></html>`);
    win.document.close();
    win.focus();
    setTimeout(() => win.print(), 400);
  };

  const handleDownload = () => {
    if (!activeReport) return;
    const blob = new Blob([activeReport.content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${activeReport.name.replace(/\s+/g, '_')}_${new Date().toISOString().slice(0, 10)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div style={{ flex: 1, display: 'flex', flexDirection: 'column' }}>
      <TopNavbar title="Reports Center 📋" subtitle="CIS Department — Generate & Export Reports" accentColor="#10B981" />
      <main style={{ flex: 1, padding: '1.5rem', overflowY: 'auto' }} className="fade-in">

        <div style={{ marginBottom: '1.5rem', padding: '1.25rem 1.5rem', background: 'linear-gradient(135deg, rgba(16,185,129,0.08), transparent)', borderRadius: '14px', border: '1px solid rgba(16,185,129,0.2)', display: 'flex', alignItems: 'center', gap: '14px' }}>
          <span style={{ fontSize: '1.8rem' }}>📋</span>
          <div>
            <h3 style={{ fontSize: '1.05rem', fontWeight: 800, margin: 0 }}>Departmental Reports Center</h3>
            <p style={{ fontSize: '0.85rem', color: 'var(--muted)', margin: '4px 0 0' }}>Generate PDF or Excel reports for any aspect of your department. Click "Generate Report" to instantly create a full, live report from real-time data scoped strictly to CIS department.</p>
          </div>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(320px, 1fr))', gap: '1rem' }}>
          {REPORTS.map(report => {
            const isGenerating = generating === report.id;
            return (
              <div key={report.id} className="glass-card" style={{ padding: '1.5rem', display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                  <div style={{ width: 48, height: 48, borderRadius: '12px', background: 'rgba(16,185,129,0.12)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '1.5rem', flexShrink: 0 }}>
                    {report.icon}
                  </div>
                  <div>
                    <h4 style={{ fontSize: '0.95rem', fontWeight: 800, margin: 0 }}>{report.name}</h4>
                    <span style={{ fontSize: '0.7rem', padding: '2px 8px', background: 'rgba(59,130,246,0.1)', color: '#3B82F6', borderRadius: '6px', fontWeight: 700 }}>{report.category}</span>
                  </div>
                </div>
                <p style={{ fontSize: '0.83rem', color: 'var(--muted)', margin: 0, lineHeight: 1.55 }}>{report.desc}</p>
                <button
                  onClick={() => generate(report)}
                  disabled={isGenerating}
                  style={{
                    padding: '9px', borderRadius: '8px',
                    background: isGenerating ? 'var(--surface-2)' : 'linear-gradient(135deg, #10B981, #3B82F6)',
                    color: isGenerating ? 'var(--muted)' : '#fff',
                    border: 'none', fontSize: '0.82rem', fontWeight: 700,
                    cursor: isGenerating ? 'not-allowed' : 'pointer', transition: 'all 0.2s'
                  }}
                >
                  {isGenerating ? '⏳ Generating with AI...' : '⚡ Generate Report'}
                </button>
              </div>
            );
          })}
        </div>
      </main>

      {/* Report Modal */}
      {activeReport && (
        <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.75)', zIndex: 500, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '1rem' }}>
          <div className="glass-card" style={{ width: '100%', maxWidth: 900, maxHeight: '90vh', display: 'flex', flexDirection: 'column', background: 'var(--surface)', borderRadius: 16, overflow: 'hidden' }}>
            {/* Modal Header */}
            <div style={{ padding: '1rem 1.5rem', borderBottom: '1px solid var(--border)', display: 'flex', justifyContent: 'space-between', alignItems: 'center', background: 'linear-gradient(135deg, rgba(16,185,129,0.1), transparent)', flexShrink: 0 }}>
              <div>
                <h3 style={{ margin: 0, fontSize: '1rem', fontWeight: 800 }}>📄 {activeReport.name}</h3>
                <p style={{ margin: '2px 0 0', fontSize: '0.75rem', color: 'var(--muted)' }}>AI-Generated · CIS Department Data · {new Date().toLocaleDateString('en-US', { dateStyle: 'long' })}</p>
              </div>
              <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
                <button onClick={handleDownload} style={{ padding: '7px 14px', background: '#10B981', color: '#fff', border: 'none', borderRadius: 8, fontSize: '0.78rem', fontWeight: 700, cursor: 'pointer' }}>
                  💾 Download (.txt)
                </button>
                <button onClick={handlePrint} style={{ padding: '7px 14px', background: '#EF4444', color: '#fff', border: 'none', borderRadius: 8, fontSize: '0.78rem', fontWeight: 700, cursor: 'pointer' }}>
                  🖨️ Print / PDF
                </button>
                <button onClick={() => setActiveReport(null)} style={{ padding: '7px 14px', background: 'var(--surface-2)', color: 'var(--text)', border: '1px solid var(--border)', borderRadius: 8, fontSize: '0.78rem', fontWeight: 700, cursor: 'pointer' }}>
                  ✕ Close
                </button>
              </div>
            </div>
            {/* Report Content */}
            <div style={{ flex: 1, overflowY: 'auto', padding: '1.25rem 1.5rem' }}>
              <pre style={{ fontFamily: 'monospace', fontSize: '0.78rem', whiteSpace: 'pre-wrap', lineHeight: 1.7, color: 'var(--text)', margin: 0 }}>
                {activeReport.content}
              </pre>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
