'use client';
import { useState } from 'react';
import TopNavbar from '@/components/layout/TopNavbar';
import {
  HR_EMPLOYEES, LEAVE_REQUESTS, PAYROLL_SUMMARY, MASTER_DEPARTMENTS, UNIVERSITY_STATS
} from '@/data/sharedMockData';

const REPORTS = [
  { id: 'HR-R01', name: 'Master Employee Roster', icon: '👥', desc: 'Complete list of all active employees with departmental details.', category: 'Employee' },
  { id: 'HR-R02', name: 'Monthly Attendance Report', icon: '📅', desc: 'Detailed attendance, late arrivals, and absence records.', category: 'Attendance' },
  { id: 'HR-R03', name: 'Leave Utilization Report', icon: '🏖️', desc: 'Employee leave balances, approved leaves, and pending requests.', category: 'Leave' },
  { id: 'HR-R04', name: 'Payroll Summary Report', icon: '💵', desc: 'Monthly salary disbursement, bonuses, and tax deduction summaries.', category: 'Payroll' },
  { id: 'HR-R05', name: 'Performance (KPI) Review', icon: '📈', desc: 'Aggregated KPI scores, supervisor reviews, and promotion recommendations.', category: 'Performance' },
  { id: 'HR-R06', name: 'Recruitment & Hiring Log', icon: '🎯', desc: 'Status of all open positions, applicant counts, and recent hires.', category: 'Recruitment' },
  { id: 'HR-R07', name: 'Department Headcount Analysis', icon: '🏢', desc: 'Workforce distribution, faculty-to-staff ratios, and vacancy tracking.', category: 'Department' },
  { id: 'HR-R08', name: 'Contract Expiration Alert', icon: '⏳', desc: 'List of employees whose contracts or probation periods are ending soon.', category: 'Alerts' },
];

const CC: Record<string, { bg: string; color: string }> = {
  Employee: { bg: 'rgba(59,130,246,0.1)', color: '#3B82F6' },
  Attendance: { bg: 'rgba(16,185,129,0.1)', color: '#10B981' },
  Leave: { bg: 'rgba(245,158,11,0.1)', color: '#F59E0B' },
  Payroll: { bg: 'rgba(139,92,246,0.1)', color: '#8B5CF6' },
  Performance: { bg: 'rgba(236,72,153,0.1)', color: '#EC4899' },
  Recruitment: { bg: 'rgba(14,165,233,0.1)', color: '#0EA5E9' },
  Department: { bg: 'rgba(99,102,241,0.1)', color: '#6366F1' },
  Alerts: { bg: 'rgba(239,68,68,0.1)', color: '#EF4444' },
};

function buildReportContent(id: string): string {
  const now = new Date();
  const ts = now.toLocaleString('en-US', { dateStyle: 'full', timeStyle: 'short' });
  const active = HR_EMPLOYEES.filter(e => e.status === 'Active');
  const faculty = HR_EMPLOYEES.filter(e => e.employeeType === 'Faculty');
  const admin = HR_EMPLOYEES.filter(e => e.employeeType === 'Admin' || e.employeeType === 'Staff');
  const lowKpi = HR_EMPLOYEES.filter(e => e.kpiScore < 70);
  const lowAttendance = HR_EMPLOYEES.filter(e => e.attendanceRate < 80);
  const pending = LEAVE_REQUESTS.filter(l => l.status === 'Pending');
  const approved = LEAVE_REQUESTS.filter(l => l.status === 'Approved');
  const contractual = HR_EMPLOYEES.filter(e => e.contractType === 'Contractual');
  const totalPayroll = HR_EMPLOYEES.reduce((s, e) => s + e.salary, 0);

  const header = `╔══════════════════════════════════════════════════════════════╗
  DAFFODIL INTERNATIONAL UNIVERSITY — HR MANAGEMENT PORTAL
  Generated: ${ts}
  Generated By: Ms. Nasrin Sultana (HR Director)
  System: EduVision AI ERP Platform
╚══════════════════════════════════════════════════════════════╝\n\n`;

  if (id === 'HR-R01') {
    const rows = HR_EMPLOYEES.map((e, i) =>
      `  ${String(i + 1).padStart(2, '0')}. ${e.name.padEnd(30)} | ${e.designation.padEnd(28)} | ${e.department.padEnd(36)} | ${e.employeeType.padEnd(8)} | ${e.contractType.padEnd(11)} | Joined: ${e.joinYear} | Status: ${e.status}`
    ).join('\n');
    return `${header}📋 MASTER EMPLOYEE ROSTER — ${UNIVERSITY_STATS.semester}
Total Employees: ${HR_EMPLOYEES.length} | Active: ${active.length} | Faculty: ${faculty.length} | Admin/Staff: ${admin.length}

${'─'.repeat(140)}
${'  #'.padEnd(5)} ${'Name'.padEnd(30)} | ${'Designation'.padEnd(28)} | ${'Department'.padEnd(36)} | ${'Type'.padEnd(8)} | ${'Contract'.padEnd(11)} | Joined  | Status
${'─'.repeat(140)}
${rows}
${'─'.repeat(140)}

SUMMARY STATISTICS:
  • Total Employees: ${HR_EMPLOYEES.length}
  • Active: ${active.length}
  • Faculty Members: ${faculty.length}
  • Admin/Staff: ${admin.length}
  • Contractual Employees: ${contractual.length}
  • Permanent Employees: ${HR_EMPLOYEES.length - contractual.length}
  • Total Monthly Payroll: ৳${totalPayroll.toLocaleString()}

AI INSIGHT:
  ✅ Staffing levels appear adequate for current student enrollment of ${UNIVERSITY_STATS.totalStudents}.
  ⚠️  ${contractual.length} employee(s) on contractual basis — review renewal timelines.
  📌 Recommend onboarding 2–3 additional faculty for CSE expansion in upcoming semester.`;
  }

  if (id === 'HR-R02') {
    const rows = HR_EMPLOYEES.map((e, i) => {
      const risk = e.attendanceRate < 80 ? '🔴 CRITICAL' : e.attendanceRate < 90 ? '🟡 LOW' : '🟢 GOOD';
      return `  ${String(i + 1).padStart(2, '0')}. ${e.name.padEnd(30)} | ${e.department.padEnd(36)} | Attendance: ${String(e.attendanceRate).padStart(3)}% | ${risk}`;
    }).join('\n');
    const avg = Math.round(HR_EMPLOYEES.reduce((s, e) => s + e.attendanceRate, 0) / HR_EMPLOYEES.length);
    return `${header}📅 MONTHLY ATTENDANCE REPORT — June 2026

OVERALL ATTENDANCE: ${avg}% (University Average)
At-Risk Employees (< 80%): ${lowAttendance.length}

${'─'.repeat(100)}
${rows}
${'─'.repeat(100)}

BREAKDOWN:
  • Attendance ≥ 95% (Excellent):  ${HR_EMPLOYEES.filter(e => e.attendanceRate >= 95).length} employees
  • Attendance 80–94% (Acceptable): ${HR_EMPLOYEES.filter(e => e.attendanceRate >= 80 && e.attendanceRate < 95).length} employees
  • Attendance < 80% (Critical):    ${lowAttendance.length} employees

CRITICAL CASES:
${lowAttendance.length > 0 ? lowAttendance.map(e => `  ⚠️  ${e.name} (${e.department}) — ${e.attendanceRate}% — Recommend formal counseling`).join('\n') : '  ✅ No critical attendance cases this month.'}

AI INSIGHT:
  📌 Overall attendance of ${avg}% is ${avg >= 85 ? 'above' : 'below'} the 85% target threshold.
  ${lowAttendance.length > 0 ? `⚠️  ${lowAttendance.length} employee(s) require HR intervention.` : '✅ All employees meeting attendance standards.'}
  🔔 Recommend monthly attendance review meetings for departments below 85%.`;
  }

  if (id === 'HR-R03') {
    const rows = LEAVE_REQUESTS.map((l, i) =>
      `  ${String(i + 1).padStart(2, '0')}. ${l.employeeName.padEnd(28)} | ${l.type.padEnd(10)} | ${l.days} days | ${l.from} → ${l.to} | ${l.status.padEnd(8)} | ${l.reason}`
    ).join('\n');
    const totalDays = LEAVE_REQUESTS.reduce((s, l) => s + l.days, 0);
    return `${header}🏖️ LEAVE UTILIZATION REPORT — July 2026

Total Leave Requests: ${LEAVE_REQUESTS.length} | Pending: ${pending.length} | Approved: ${approved.length}
Total Leave Days Requested: ${totalDays} days

${'─'.repeat(110)}
${'  #'.padEnd(5)} ${'Employee'.padEnd(28)} | ${'Type'.padEnd(10)} | Days | Date Range              | Status   | Reason
${'─'.repeat(110)}
${rows}
${'─'.repeat(110)}

LEAVE BALANCE SUMMARY (Faculty):
${HR_EMPLOYEES.slice(0, 5).map(e => `  • ${e.name.padEnd(30)} — Balance: ${e.leaveBalance} days remaining`).join('\n')}

AI INSIGHT:
  📌 ${pending.length} leave request(s) awaiting HR approval — action required.
  ✅ Leave utilization is within normal range for this time of year.
  🔔 Peak leave period expected August–September. Plan coverage in advance.`;
  }

  if (id === 'HR-R04') {
    const rows = HR_EMPLOYEES.map((e, i) => {
      const tax = Math.round(e.salary * 0.1);
      const net = e.salary - tax;
      return `  ${String(i + 1).padStart(2, '0')}. ${e.name.padEnd(30)} | ${e.designation.padEnd(28)} | Gross: ৳${e.salary.toLocaleString().padStart(7)} | Tax: ৳${tax.toLocaleString().padStart(6)} | Net: ৳${net.toLocaleString().padStart(7)}`;
    }).join('\n');
    const totalNet = HR_EMPLOYEES.reduce((s, e) => s + Math.round(e.salary * 0.9), 0);
    const totalTax = HR_EMPLOYEES.reduce((s, e) => s + Math.round(e.salary * 0.1), 0);
    return `${header}💵 PAYROLL SUMMARY REPORT — ${PAYROLL_SUMMARY.month}

Status: ${PAYROLL_SUMMARY.status} ✅
Total Employees Paid: ${PAYROLL_SUMMARY.totalEmployeesPaid}
Total Gross Payroll: ৳${totalPayroll.toLocaleString()}
Total Tax Deducted: ৳${totalTax.toLocaleString()}
Total Net Disbursed: ৳${totalNet.toLocaleString()}

${'─'.repeat(115)}
${'  #'.padEnd(5)} ${'Employee'.padEnd(30)} | ${'Designation'.padEnd(28)} | Gross Salary | Tax (10%) | Net Pay
${'─'.repeat(115)}
${rows}
${'─'.repeat(115)}

PAYROLL STATISTICS:
  • Highest Salary: ৳${Math.max(...HR_EMPLOYEES.map(e => e.salary)).toLocaleString()}
  • Lowest Salary:  ৳${Math.min(...HR_EMPLOYEES.map(e => e.salary)).toLocaleString()}
  • Average Salary: ৳${Math.round(totalPayroll / HR_EMPLOYEES.length).toLocaleString()}
  • Pending Clearances: ${PAYROLL_SUMMARY.pendingClearances}
  • Tax Deducted YTD: ৳${PAYROLL_SUMMARY.taxDeductedYTD.toLocaleString()}

AI INSIGHT:
  ✅ Payroll disbursement completed on schedule for ${PAYROLL_SUMMARY.month}.
  ⚠️  ${PAYROLL_SUMMARY.pendingClearances} clearance(s) still pending — resolve before next cycle.
  📌 Faculty salary band is competitive for the Dhaka university market.`;
  }

  if (id === 'HR-R05') {
    const sorted = [...HR_EMPLOYEES].sort((a, b) => b.kpiScore - a.kpiScore);
    const rows = sorted.map((e, i) => {
      const rating = e.kpiScore >= 85 ? '⭐ Excellent' : e.kpiScore >= 70 ? '👍 Good' : '⚠️  Needs Improvement';
      return `  ${String(i + 1).padStart(2, '0')}. ${e.name.padEnd(30)} | KPI: ${String(e.kpiScore).padStart(3)}% | ${rating}`;
    }).join('\n');
    const avgKpi = Math.round(HR_EMPLOYEES.reduce((s, e) => s + e.kpiScore, 0) / HR_EMPLOYEES.length);
    return `${header}📈 PERFORMANCE (KPI) REVIEW — ${UNIVERSITY_STATS.semester}

University Average KPI: ${avgKpi}%
Excellent (≥85%): ${HR_EMPLOYEES.filter(e => e.kpiScore >= 85).length} | Good (70–84%): ${HR_EMPLOYEES.filter(e => e.kpiScore >= 70 && e.kpiScore < 85).length} | Needs Improvement (<70%): ${lowKpi.length}

${'─'.repeat(70)}
EMPLOYEE KPI RANKINGS:
${'─'.repeat(70)}
${rows}
${'─'.repeat(70)}

PROMOTION RECOMMENDATIONS:
${sorted.filter(e => e.kpiScore >= 85).map(e => `  ⭐ ${e.name} (${e.kpiScore}%) — Recommended for performance increment/promotion`).join('\n') || '  None this cycle.'}

IMPROVEMENT PLANS REQUIRED:
${lowKpi.map(e => `  ⚠️  ${e.name} (${e.kpiScore}%) — Mandatory performance improvement plan required`).join('\n') || '  ✅ All employees meeting KPI targets.'}

AI INSIGHT:
  📌 Department average KPI of ${avgKpi}% is ${avgKpi >= 75 ? 'satisfactory' : 'below target'}.
  🔔 Recommend quarterly KPI review meetings to maintain upward trajectory.`;
  }

  if (id === 'HR-R06') {
    return `${header}🎯 RECRUITMENT & HIRING LOG — ${UNIVERSITY_STATS.semester}

OPEN POSITIONS:
  01. CSE Department — Assistant Professor (Machine Learning) — 12 applicants — In Review
  02. CIS Department — Lecturer (Web Development) — 8 applicants — Shortlisted
  03. Administration — Executive Officer — 22 applicants — Final Round
  04. IT Support — Network Engineer — 5 applicants — Open

RECENT HIRES (Last 6 Months):
${'─'.repeat(80)}
${HR_EMPLOYEES.filter(e => e.joinYear >= 2020).map((e, i) =>
      `  ${String(i + 1).padStart(2, '0')}. ${e.name.padEnd(30)} | ${e.designation} | Joined: ${e.joinYear}`
    ).join('\n')}
${'─'.repeat(80)}

RECRUITMENT METRICS:
  • Total Open Positions: 4
  • Total Applications Received: 47
  • Average Time-to-Hire: 32 days
  • Offer Acceptance Rate: 78%
  • Internal Promotions (YTD): 2

AI INSIGHT:
  📌 4 open positions need to be filled before Fall 2026 semester start.
  ⚠️  ML/AI faculty shortage — prioritize CSE hiring to meet student demand.
  ✅ Retention rate of 94% — above industry average for private universities.`;
  }

  if (id === 'HR-R07') {
    const rows = MASTER_DEPARTMENTS.map((d, i) =>
      `  ${String(i + 1).padStart(2, '0')}. ${d.name.padEnd(44)} | Head: ${d.head.padEnd(30)} | Students: ${String(d.students).padStart(4)} | Teachers: ${String(d.teachers).padStart(3)} | Ratio: 1:${Math.round(d.students / d.teachers)}`
    ).join('\n');
    const totalTeachers = MASTER_DEPARTMENTS.reduce((s, d) => s + d.teachers, 0);
    const totalStudents = MASTER_DEPARTMENTS.reduce((s, d) => s + d.students, 0);
    return `${header}🏢 DEPARTMENT HEADCOUNT ANALYSIS — ${UNIVERSITY_STATS.semester}

University Total: ${totalStudents} Students | ${totalTeachers} Faculty | ${MASTER_DEPARTMENTS.length} Departments
Overall Student-Faculty Ratio: 1:${Math.round(totalStudents / totalTeachers)}

${'─'.repeat(120)}
${rows}
${'─'.repeat(120)}

WORKLOAD ANALYSIS:
${MASTER_DEPARTMENTS.map(d => {
      const ratio = Math.round(d.students / d.teachers);
      const flag = ratio > 25 ? '🔴 OVERLOADED' : ratio > 18 ? '🟡 HIGH' : '🟢 NORMAL';
      return `  • ${d.shortName}: ${ratio}:1 ratio — ${flag}`;
    }).join('\n')}

AI INSIGHT:
  📌 Mathematics department has the highest student-to-teacher ratio — hire 2 more faculty immediately.
  ⚠️  Pharmacy department at-risk rate of 28% — may indicate understaffing.
  ✅ BBA department maintains optimal staffing balance.`;
  }

  if (id === 'HR-R08') {
    const expiring = contractual;
    return `${header}⏳ CONTRACT EXPIRATION ALERT — As of ${ts}

Employees on Contractual Basis: ${contractual.length}
Permanent Employees: ${HR_EMPLOYEES.length - contractual.length}

${'─'.repeat(90)}
CONTRACTS EXPIRING / REQUIRING RENEWAL:
${'─'.repeat(90)}
${expiring.length > 0 ? expiring.map((e, i) =>
      `  ${String(i + 1).padStart(2, '0')}. ${e.name.padEnd(30)} | ${e.designation.padEnd(25)} | ${e.department} | Joined: ${e.joinYear} | 🔔 Review required`
    ).join('\n') : '  ✅ No contracts expiring in the next 30 days.'}
${'─'.repeat(90)}

PROBATIONARY EMPLOYEES (< 1 Year):
${HR_EMPLOYEES.filter(e => e.joinYear >= 2025).map(e =>
      `  ⏳ ${e.name} — ${e.designation} — ${e.department} — Probation review due`
    ).join('\n') || '  ✅ No employees currently in probationary period.'}

RECOMMENDED ACTIONS:
${expiring.map(e => `  📋 Initiate contract renewal discussion with ${e.name} — HR meeting required`).join('\n') || '  ✅ No immediate contract actions required.'}

AI INSIGHT:
  📌 All contractual employee renewals should be initiated 60 days before expiry.
  🔔 Set automated reminders for contract renewal 90, 60, and 30 days in advance.`;
  }

  return `${header}📊 Report data generated successfully.\nTimestamp: ${ts}`;
}

export default function HRReportsPage() {
  const [generating, setGenerating] = useState<string | null>(null);
  const [activeReport, setActiveReport] = useState<{ id: string; name: string; content: string } | null>(null);

  const generate = (report: typeof REPORTS[0]) => {
    setGenerating(report.id);
    setTimeout(() => {
      const content = buildReportContent(report.id);
      setActiveReport({ id: report.id, name: report.name, content });
      setGenerating(null);
    }, 1200);
  };

  const handlePrint = () => {
    if (!activeReport) return;
    const win = window.open('', '_blank');
    if (!win) return;
    win.document.write(`<html><head><title>${activeReport.name}</title>
      <style>body{font-family:monospace;font-size:13px;padding:24px;white-space:pre-wrap;line-height:1.6;color:#0f172a;}
      h1{font-size:16px;}@media print{body{font-size:11px;}}</style></head>
      <body><pre>${activeReport.content}</pre></body></html>`);
    win.document.close();
    win.focus();
    setTimeout(() => win.print(), 400);
  };

  const handleDownload = () => {
    if (!activeReport) return;
    const blob = new Blob([activeReport.content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${activeReport.name.replace(/\s+/g, '_')}_${new Date().toISOString().slice(0, 10)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div style={{ flex: 1, display: 'flex', flexDirection: 'column' }}>
      <TopNavbar title="HR Reports Center 📋" subtitle="AI-Generated HR, Payroll & Attendance Reports" accentColor="#0EA5E9" />
      <main style={{ flex: 1, padding: '1.5rem', overflowY: 'auto' }} className="fade-in">

        <div style={{ marginBottom: '1.5rem', padding: '1.25rem 1.5rem', background: 'linear-gradient(135deg, rgba(14,165,233,0.08), transparent)', borderRadius: '14px', border: '1px solid rgba(14,165,233,0.2)', display: 'flex', alignItems: 'center', gap: '14px' }}>
          <span style={{ fontSize: '1.8rem' }}>📊</span>
          <div>
            <h3 style={{ fontSize: '1.05rem', fontWeight: 800, margin: 0 }}>AI-Powered HR Report Generator</h3>
            <p style={{ fontSize: '0.85rem', color: 'var(--muted)', margin: '4px 0 0' }}>
              Click "Generate Report" to instantly create a full, live report from real-time HR data. Reports include employee roster, attendance, payroll, KPI, and more.
            </p>
          </div>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(320px, 1fr))', gap: '1rem' }}>
          {REPORTS.map(report => {
            const cc = CC[report.category] || { bg: 'var(--surface-2)', color: 'var(--muted)' };
            const isGenerating = generating === report.id;
            return (
              <div key={report.id} className="glass-card" style={{ padding: '1.5rem', display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                  <div style={{ width: 48, height: 48, borderRadius: '12px', background: cc.bg, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '1.5rem', flexShrink: 0 }}>
                    {report.icon}
                  </div>
                  <div>
                    <h4 style={{ fontSize: '0.95rem', fontWeight: 800, margin: 0 }}>{report.name}</h4>
                    <span style={{ fontSize: '0.7rem', padding: '2px 8px', background: cc.bg, color: cc.color, borderRadius: '6px', fontWeight: 700 }}>{report.category}</span>
                  </div>
                </div>
                <p style={{ fontSize: '0.83rem', color: 'var(--muted)', margin: 0, lineHeight: 1.55 }}>{report.desc}</p>
                <button
                  onClick={() => generate(report)}
                  disabled={isGenerating}
                  style={{
                    padding: '9px', borderRadius: '8px',
                    background: isGenerating ? 'var(--surface-2)' : 'linear-gradient(135deg, #0EA5E9, #3B82F6)',
                    color: isGenerating ? 'var(--muted)' : '#fff',
                    border: 'none', fontSize: '0.82rem', fontWeight: 700,
                    cursor: isGenerating ? 'not-allowed' : 'pointer', transition: 'all 0.2s'
                  }}
                >
                  {isGenerating ? '⏳ Generating with AI...' : '⚡ Generate Report'}
                </button>
              </div>
            );
          })}
        </div>
      </main>

      {/* Report Modal */}
      {activeReport && (
        <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.75)', zIndex: 500, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '1rem' }}>
          <div className="glass-card" style={{ width: '100%', maxWidth: 900, maxHeight: '90vh', display: 'flex', flexDirection: 'column', background: 'var(--surface)', borderRadius: 16, overflow: 'hidden' }}>
            {/* Modal Header */}
            <div style={{ padding: '1rem 1.5rem', borderBottom: '1px solid var(--border)', display: 'flex', justifyContent: 'space-between', alignItems: 'center', background: 'linear-gradient(135deg, rgba(14,165,233,0.1), transparent)', flexShrink: 0 }}>
              <div>
                <h3 style={{ margin: 0, fontSize: '1rem', fontWeight: 800 }}>📄 {activeReport.name}</h3>
                <p style={{ margin: '2px 0 0', fontSize: '0.75rem', color: 'var(--muted)' }}>AI-Generated · Live Data · {new Date().toLocaleDateString('en-US', { dateStyle: 'long' })}</p>
              </div>
              <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
                <button onClick={handleDownload} style={{ padding: '7px 14px', background: '#10B981', color: '#fff', border: 'none', borderRadius: 8, fontSize: '0.78rem', fontWeight: 700, cursor: 'pointer' }}>
                  💾 Download (.txt)
                </button>
                <button onClick={handlePrint} style={{ padding: '7px 14px', background: '#EF4444', color: '#fff', border: 'none', borderRadius: 8, fontSize: '0.78rem', fontWeight: 700, cursor: 'pointer' }}>
                  🖨️ Print / PDF
                </button>
                <button onClick={() => setActiveReport(null)} style={{ padding: '7px 14px', background: 'var(--surface-2)', color: 'var(--text)', border: '1px solid var(--border)', borderRadius: 8, fontSize: '0.78rem', fontWeight: 700, cursor: 'pointer' }}>
                  ✕ Close
                </button>
              </div>
            </div>
            {/* Report Content */}
            <div style={{ flex: 1, overflowY: 'auto', padding: '1.25rem 1.5rem' }}>
              <pre style={{ fontFamily: 'monospace', fontSize: '0.78rem', whiteSpace: 'pre-wrap', lineHeight: 1.7, color: 'var(--text)', margin: 0 }}>
                {activeReport.content}
              </pre>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
