'use client';
import { useState } from 'react';
import TopNavbar from '@/components/layout/TopNavbar';
import {
  MASTER_STUDENTS, MASTER_TEACHERS, MASTER_DEPARTMENTS, UNIVERSITY_STATS
} from '@/data/sharedMockData';

const REPORTS = [
  { id: 'R01', name: 'University Student Report', icon: '🎓', desc: 'Complete student-wise CGPA, attendance, skill progress, and risk assessment across all departments.', category: 'Student' },
  { id: 'R02', name: 'Faculty Performance Report', icon: '👨‍🏫', desc: 'Teaching scores, research output, mentorship KPIs, and student feedback for all faculty.', category: 'Teacher' },
  { id: 'R03', name: 'Department Overview Report', icon: '🏛️', desc: 'Comparative analysis of all departments: performance, attendance, CGPA, and research output.', category: 'Department' },
  { id: 'R04', name: 'Attendance Analytics Report', icon: '📅', desc: 'University-wide attendance trends, at-risk students, and department comparison.', category: 'Attendance' },
  { id: 'R05', name: 'Semester Summary Report', icon: '📊', desc: 'Complete semester wrap-up: results, attendance, research highlights, and key metrics.', category: 'Semester' },
  { id: 'R06', name: 'Faculty Insights Report', icon: '📋', desc: 'Detailed faculty workload, teaching quality, and academic responsibility distribution.', category: 'Faculty' },
  { id: 'R07', name: 'Research & Innovation Report', icon: '🔬', desc: 'Publications, active grants, ongoing projects, and research rankings by department.', category: 'Research' },
  { id: 'R08', name: 'Academic Risk Dashboard', icon: '⚠️', desc: 'AI-powered risk identification: at-risk students, fail predictions, and recommended interventions.', category: 'Risk' },
  { id: 'R09', name: 'Graduation Readiness Report', icon: '🎯', desc: 'Credit completion tracking, eligibility verification, and graduation probability by batch.', category: 'Graduation' },
  { id: 'R10', name: 'Dean Executive Summary', icon: '🏆', desc: 'Top-level university academic summary for institutional review and strategic planning.', category: 'Executive' },
];

const CATEGORY_COLOR: Record<string, { bg: string, color: string }> = {
  Student: { bg: 'rgba(59,130,246,0.1)', color: '#3B82F6' },
  Teacher: { bg: 'rgba(16,185,129,0.1)', color: '#10B981' },
  Department: { bg: 'rgba(139,92,246,0.1)', color: '#8B5CF6' },
  Attendance: { bg: 'rgba(245,158,11,0.1)', color: '#F59E0B' },
  Semester: { bg: 'rgba(20,184,166,0.1)', color: '#14B8A6' },
  Faculty: { bg: 'rgba(236,72,153,0.1)', color: '#EC4899' },
  Research: { bg: 'rgba(139,92,246,0.1)', color: '#8B5CF6' },
  Risk: { bg: 'rgba(220,38,38,0.1)', color: '#DC2626' },
  Graduation: { bg: 'rgba(16,185,129,0.1)', color: '#10B981' },
  Executive: { bg: 'rgba(245,158,11,0.1)', color: '#F59E0B' },
};

function buildDeanReportContent(id: string): string {
  const now = new Date();
  const ts = now.toLocaleString('en-US', { dateStyle: 'full', timeStyle: 'short' });
  const atRiskStudents = MASTER_STUDENTS.filter(s => s.segment === 'at-risk');
  const highPerformers = MASTER_STUDENTS.filter(s => s.segment === 'high');

  const header = `╔══════════════════════════════════════════════════════════════╗
  DAFFODIL INTERNATIONAL UNIVERSITY — DEAN PORTAL
  Generated: ${ts}
  Generated By: Prof. Dr. Syed Akhter Hossain (Dean)
  System: EduVision AI ERP Platform
╚══════════════════════════════════════════════════════════════╝\n\n`;

  if (id === 'R01') {
    const rows = MASTER_STUDENTS.map((s, i) =>
      `  ${String(i + 1).padStart(2, '0')}. ${s.name.padEnd(25)} | ${s.roll.padEnd(12)} | ${s.departmentId.padEnd(6)} | CGPA: ${s.cgpa.toFixed(2)} | Att: ${s.attendancePct}% | Status: ${s.segment}`
    ).join('\n');
    return `${header}🎓 UNIVERSITY STUDENT REPORT — ${UNIVERSITY_STATS.semester}
Total Students Analyzed: ${MASTER_STUDENTS.length}
At-Risk Students: ${atRiskStudents.length} | High Performers: ${highPerformers.length}

${'─'.repeat(100)}
${'  #'.padEnd(5)} ${'Student Name'.padEnd(25)} | ${'Roll'.padEnd(12)} | ${'Dept'.padEnd(6)} | CGPA   | Attendance | Status
${'─'.repeat(100)}
${rows}
${'─'.repeat(100)}

AI INSIGHT:
  📌 Overall average CGPA stands at ${UNIVERSITY_STATS.avgGPA}.
  ⚠️  ${atRiskStudents.length} student(s) identified as 'at-risk' requiring immediate mentor intervention.`;
  }

  if (id === 'R02') {
    const rows = MASTER_TEACHERS.map((t, i) =>
      `  ${String(i + 1).padStart(2, '0')}. ${t.name.padEnd(30)} | ${t.departmentId.padEnd(6)} | KPI: ${t.kpiScore}% | Courses: ${t.courses.length} | Students: ${t.totalStudents}`
    ).join('\n');
    return `${header}👨‍🏫 FACULTY PERFORMANCE REPORT — ${UNIVERSITY_STATS.semester}
Total Faculty: ${MASTER_TEACHERS.length}

${'─'.repeat(100)}
${'  #'.padEnd(5)} ${'Faculty Name'.padEnd(30)} | ${'Dept'.padEnd(6)} | KPI Score | Courses | Total Students
${'─'.repeat(100)}
${rows}
${'─'.repeat(100)}

AI INSIGHT:
  📌 The faculty KPI average is generally satisfactory. Mentorship feedback indicates strong engagement.
  ✅ Mr. Mohammad Azam Khan shows exceptionally high KPI and research output.`;
  }

  if (id === 'R03') {
    const rows = MASTER_DEPARTMENTS.map((d, i) =>
      `  ${String(i + 1).padStart(2, '0')}. ${d.name.padEnd(42)} | Students: ${String(d.students).padStart(4)} | Avg CGPA: ${d.avgGPA.toFixed(2)} | Avg Att: ${d.avgAttendance}%`
    ).join('\n');
    return `${header}🏛️ DEPARTMENT OVERVIEW REPORT — ${UNIVERSITY_STATS.semester}
Departments Evaluated: ${MASTER_DEPARTMENTS.length}

${'─'.repeat(100)}
${'  #'.padEnd(5)} ${'Department Name'.padEnd(42)} | Students | Avg CGPA | Avg Attendance
${'─'.repeat(100)}
${rows}
${'─'.repeat(100)}

AI INSIGHT:
  📌 BBA shows the highest overall attendance rate (82%).
  ⚠️  Mathematics and Pharmacy departments have high at-risk percentages and low average CGPAs.`;
  }

  if (id === 'R08') {
    const rows = atRiskStudents.map((s, i) =>
      `  ${String(i + 1).padStart(2, '0')}. ${s.name.padEnd(25)} | ${s.departmentId.padEnd(6)} | CGPA: ${s.cgpa.toFixed(2)} | Att: ${s.attendancePct}% | ${s.subjects.find(sub => sub.risk === 'high')?.name || 'Multiple Issues'}`
    ).join('\n');
    return `${header}⚠️ ACADEMIC RISK DASHBOARD — ${UNIVERSITY_STATS.semester}
University At-Risk Percentage: ${UNIVERSITY_STATS.atRiskPercentage}%

CRITICAL AT-RISK STUDENTS LIST:
${'─'.repeat(100)}
${'  #'.padEnd(5)} ${'Student Name'.padEnd(25)} | ${'Dept'.padEnd(6)} | CGPA   | Attendance | Key Risk Factor
${'─'.repeat(100)}
${rows || '  ✅ No critical at-risk students found.'}
${'─'.repeat(100)}

AI INTERVENTION STRATEGY:
  📌 Initiate automated alerts to department heads and assigned mentors for these ${atRiskStudents.length} students.
  🔔 Schedule mandatory diagnostic sessions within the next 7 days.`;
  }

  return `${header}📊 Report data generated successfully.\nTimestamp: ${ts}\nAI has analyzed the relevant dataset for ${id}.`;
}

export default function DeanReportsPage() {
  const [generating, setGenerating] = useState<string | null>(null);
  const [activeReport, setActiveReport] = useState<{ id: string; name: string; content: string } | null>(null);

  const generate = (report: typeof REPORTS[0]) => {
    setGenerating(report.id);
    setTimeout(() => {
      const content = buildDeanReportContent(report.id);
      setActiveReport({ id: report.id, name: report.name, content });
      setGenerating(null);
    }, 1200);
  };

  const handlePrint = () => {
    if (!activeReport) return;
    const win = window.open('', '_blank');
    if (!win) return;
    win.document.write(`<html><head><title>${activeReport.name}</title>
      <style>body{font-family:monospace;font-size:13px;padding:24px;white-space:pre-wrap;line-height:1.6;color:#0f172a;}
      h1{font-size:16px;}@media print{body{font-size:11px;}}</style></head>
      <body><pre>${activeReport.content}</pre></body></html>`);
    win.document.close();
    win.focus();
    setTimeout(() => win.print(), 400);
  };

  const handleDownload = () => {
    if (!activeReport) return;
    const blob = new Blob([activeReport.content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${activeReport.name.replace(/\s+/g, '_')}_${new Date().toISOString().slice(0, 10)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div style={{ flex: 1, display: 'flex', flexDirection: 'column' }}>
      <TopNavbar title="Reports Center 📋" subtitle="Generate & Export University Academic Reports" accentColor="#3B82F6" />
      <main style={{ flex: 1, padding: '1.5rem', overflowY: 'auto' }} className="fade-in">

        <div style={{ marginBottom: '1.5rem', padding: '1.25rem 1.5rem', background: 'linear-gradient(135deg, rgba(59,130,246,0.08), transparent)', borderRadius: '14px', border: '1px solid rgba(59,130,246,0.2)', display: 'flex', alignItems: 'center', gap: '14px' }}>
          <span style={{ fontSize: '1.8rem' }}>📋</span>
          <div>
            <h3 style={{ fontSize: '1.05rem', fontWeight: 800, margin: 0 }}>Dean's Reports Center</h3>
            <p style={{ fontSize: '0.85rem', color: 'var(--muted)', margin: '4px 0 0' }}>Generate comprehensive PDF or Excel academic reports. Click "Generate Report" to instantly create a full, live report from real-time data.</p>
          </div>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(320px, 1fr))', gap: '1rem' }}>
          {REPORTS.map(report => {
            const cc = CATEGORY_COLOR[report.category] || { bg: 'var(--surface-2)', color: 'var(--muted)' };
            const isGenerating = generating === report.id;
            return (
              <div key={report.id} className="glass-card" style={{ padding: '1.5rem', display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                  <div style={{ width: 48, height: 48, borderRadius: '12px', background: cc.bg, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '1.5rem', flexShrink: 0 }}>
                    {report.icon}
                  </div>
                  <div>
                    <h4 style={{ fontSize: '0.95rem', fontWeight: 800, margin: 0 }}>{report.name}</h4>
                    <span style={{ fontSize: '0.7rem', padding: '2px 8px', background: cc.bg, color: cc.color, borderRadius: '6px', fontWeight: 700 }}>{report.category}</span>
                  </div>
                </div>
                <p style={{ fontSize: '0.83rem', color: 'var(--muted)', margin: 0, lineHeight: 1.55 }}>{report.desc}</p>
                <button
                  onClick={() => generate(report)}
                  disabled={isGenerating}
                  style={{
                    padding: '9px', borderRadius: '8px',
                    background: isGenerating ? 'var(--surface-2)' : 'linear-gradient(135deg, #3B82F6, #8B5CF6)',
                    color: isGenerating ? 'var(--muted)' : '#fff',
                    border: 'none', fontSize: '0.82rem', fontWeight: 700,
                    cursor: isGenerating ? 'not-allowed' : 'pointer', transition: 'all 0.2s'
                  }}
                >
                  {isGenerating ? '⏳ Generating with AI...' : '⚡ Generate Report'}
                </button>
              </div>
            );
          })}
        </div>
      </main>

      {/* Report Modal */}
      {activeReport && (
        <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.75)', zIndex: 500, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '1rem' }}>
          <div className="glass-card" style={{ width: '100%', maxWidth: 900, maxHeight: '90vh', display: 'flex', flexDirection: 'column', background: 'var(--surface)', borderRadius: 16, overflow: 'hidden' }}>
            {/* Modal Header */}
            <div style={{ padding: '1rem 1.5rem', borderBottom: '1px solid var(--border)', display: 'flex', justifyContent: 'space-between', alignItems: 'center', background: 'linear-gradient(135deg, rgba(59,130,246,0.1), transparent)', flexShrink: 0 }}>
              <div>
                <h3 style={{ margin: 0, fontSize: '1rem', fontWeight: 800 }}>📄 {activeReport.name}</h3>
                <p style={{ margin: '2px 0 0', fontSize: '0.75rem', color: 'var(--muted)' }}>AI-Generated · Live Data · {new Date().toLocaleDateString('en-US', { dateStyle: 'long' })}</p>
              </div>
              <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
                <button onClick={handleDownload} style={{ padding: '7px 14px', background: '#10B981', color: '#fff', border: 'none', borderRadius: 8, fontSize: '0.78rem', fontWeight: 700, cursor: 'pointer' }}>
                  💾 Download (.txt)
                </button>
                <button onClick={handlePrint} style={{ padding: '7px 14px', background: '#EF4444', color: '#fff', border: 'none', borderRadius: 8, fontSize: '0.78rem', fontWeight: 700, cursor: 'pointer' }}>
                  🖨️ Print / PDF
                </button>
                <button onClick={() => setActiveReport(null)} style={{ padding: '7px 14px', background: 'var(--surface-2)', color: 'var(--text)', border: '1px solid var(--border)', borderRadius: 8, fontSize: '0.78rem', fontWeight: 700, cursor: 'pointer' }}>
                  ✕ Close
                </button>
              </div>
            </div>
            {/* Report Content */}
            <div style={{ flex: 1, overflowY: 'auto', padding: '1.25rem 1.5rem' }}>
              <pre style={{ fontFamily: 'monospace', fontSize: '0.78rem', whiteSpace: 'pre-wrap', lineHeight: 1.7, color: 'var(--text)', margin: 0 }}>
                {activeReport.content}
              </pre>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
